#################################################################
###################### NexT Configuration #######################
#################################################################

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
  sidebar: source/_data/sidebar.njk
  footer: source/_data/footer.njk
  variable: source/_data/variables.styl
  style: source/_data/styles.styl


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

footer:
  since: 2020
  icon:
    name: fa fa-heart
    animated: true
    color: "#f00"
  copyright: Jueee/Yongqiang Wei
  powered: false

creative_commons:
  license: by-nc-sa
  sidebar: true


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini

darkmode: true


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  home: / || fa fa-bell
  archives: /archives/ || fa fa-archive
  categories: /categories || fa fa-fw fa-th
  tags: /tags || fa fa-fw fa-tags
  nodes: /nodes || fa fa-object-group
  Docs:
    default: /docs/ || fa fa-book

    Getting Started:
      default: /getting-started/ || fa fa-flag
      Installation: /installation.html || fa fa-download
      Deployment: /deployment.html || fa fa-upload
      Configuration: /configuration.html || fa fa-wrench
      Internationalization: /internationalization.html || fa fa-globe
      Update from 5.x: /update-from-v5.html || fa fa-retweet

    Theme Settings:
      default: /theme-settings/ || fa fa-star
      Footer: /footer.html || far fa-swatchbook
      Sidebar: /sidebar.html || fa fa-bars
      Posts: /posts.html || fa fa-paragraph
      Custom Pages: /custom-pages.html || far fa-edit
      Custom Files: /custom-files.html || fa fa-palette
      SEO: /seo.html || fa fa-external-link-square-alt
      Front Matter: /front-matter.html || fa fa-heading

    Third Party Services:
      default: /third-party-services/ || fa fa-puzzle-piece
      Math Equations: /math-equations.html || fa fa-square-root-alt
      Comment Systems: /comments.html || far fa-comment
      Statistics and Analytics: /statistics-and-analytics.html || fa fa-chart-pie
      Post Widgets: /post-widgets.html || fa fa-gift
      Search Services: /search-services.html || fa fa-search-plus
      Chat Services: /chat-services.html || fa fa-comments
      External Libraries: /external-libraries.html || fa fa-plug

    Tag Plugins:
      default: /tag-plugins/ || fa fa-rocket
      Button: /button.html || fa fa-cube
      Caniuse: /caniuse.html || fa fa-signal
      Group Pictures: /group-pictures.html || far fa-images
      Label: /label.html || fa fa-hat-wizard
      Link Grid: /link-grid.html || fa fa-grip-vertical
      Mermaid: /mermaid.html || fa fa-project-diagram
      Note: /note.html || fa fa-adjust
      PDF: /pdf.html || far fa-file-pdf
      Tabs: /tabs.html || fa fa-columns

    Advanced Settings: /advanced-settings.html || fa fa-cog
    Troubleshooting: /troubleshooting.html || fa fa-life-ring

  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

menu_settings:
  icons: true
  badges: true
  tags: true


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

avatar:
  url: /images/basic/logo.jpg
  rounded: true
  rotated: true

social:
  GitHub: https://github.com/Jueee || fab fa-github
  E-Mail: mailto:hellojue@foxmail.com || fa fa-envelope
  RSS: /atom.xml || fa fa-rss

social_icons:
  enable: true
  icons_only: true
  transition: true

toc:
  enable: true
  number: true
  wrap: true
  expand_all: true
  max_depth: 9

links:
  docker 相关学习笔记: https://jueee.github.io/docker-doc/
  kubernetes 相关学习笔记: https://jueee.github.io/kubernetes-doc/
  设计模式相关学习笔记: https://jueee.github.io/design-patterns/
  Effective Java 学习笔记: https://jueee.github.io/effective-Java/
  Java 并发编程学习笔记: https://jueee.github.io/ConcurrencyWithJava/
  Java 测试驱动开发学习笔记: https://jueee.github.io/JavaTestDrivenDev/
  Java 8 函数式编程学习笔记: https://jueee.github.io/Java8Lambdas/

# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

post_meta:
  updated_at:
    enable: false

symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: true

post_edit:
  enable: false
  url: https://github.com/Jueee/jueee-blog/edit/master/source/


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

mobile_layout_economy: true

codeblock:
  theme:
    light: default
    dark: tomorrow-night
  copy_button:
    enable: true
    style: default

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

github_banner:
  enable: true
  permalink: https://github.com/Jueee/
  title: Fork me on GitHub


# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

index_with_subtitle: true

exturl: true

google-site-verification: EOcKnfaSWdV1p3pQylUZvIx2N977P3HKwO8tQCXWxUQ

related_posts:
  enable: true
# ============================================================= #
# =============== Third Party Services Settings =============== #
# ============================================================= #

math:
  per_page: true
  mathjax:
    enable: true

pjax: true

mediumzoom: true


# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

comments:
  lazyload: true

disqus:
  enable: false
  shortname: theme-next
  count: true

valine:
  enable: true
  appId:  p5BeaWTTwjpAjNFu85LdGhaE-gzGzoHsz
  appKey:  UjjFeqPU2GMhIUJUYBh16SE0
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  meta: [nick, mail, link] # Custom comment header
  pageSize: 10 # pagination size
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html
  comment_count: true # If false, comment count will only be displayed in post page, not in home page
  recordIP: false # Whether to record the commenter IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)

# ============================================================= #
# ================= Statistics and Analytics （统计和分析）================== #
# ============================================================= #
# Google Analytics
google_analytics:
  tracking_id: UA-175024528-1
  only_pageview: false
# Baidu Analytics ID
baidu_analytics: d11c8b9bc802239c2cc46ff39d3faf79

# 不蒜子计数
busuanzi_count:
  enable: true
  total_visitors: true
  total_visitors_icon: fa fa-user
  total_views: true
  total_views_icon: fa fa-eye
  post_views: true
  post_views_icon: fa fa-eye
# ============================================================= #
# ====================== Search Services （搜索服务）====================== #
# ============================================================= #

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true

mermaid:
  enable: true

# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

motion:
  enable: true

vendors:
  anime: //cdn.jsdelivr.net/npm/animejs@3/lib/anime.min.js
  fontawesome: //cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css
