#################################################################
###################### NexT Configuration #######################
#################################################################
favicon:
  small: /images/basic/jue.ico
  medium: /images/basic/jue.ico
# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
  sidebar: source/_data/sidebar.njk
  footer: source/_data/footer.njk
  variable: source/_data/variables.styl
  style: source/_data/styles.styl


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

footer:
  since: 2020
  icon:
    name: fa fa-heart
    animated: true
    color: "#f00"
  copyright: Jueee/Yongqiang Wei
  powered: false

# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini

darkmode: true


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  home: / || fa fa-bell
  archives: /archives/ || fa fa-archive
  categories: /categories || fa fa-fw fa-th
  tags: /tags || fa fa-fw fa-tags
  nodes: /nodes || fa fa-object-group
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

menu_settings:
  icons: true
  badges: true
  tags: true


# ============================================================= #
# ===================== Sidebar Settings（侧边栏设置） ====================== #
# ============================================================= #

sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

avatar:
  url: /images/basic/logo.jpg
  rounded: true
  rotated: true

social:
  GitHub: https://github.com/Jueee || fab fa-github
  E-Mail: mailto:hellojue@foxmail.com || fa fa-envelope
  RSS: /atom.xml || fa fa-rss

social_icons:
  enable: true
  icons_only: true
  transition: true

toc:
  enable: true
  number: true
  wrap: true
  expand_all: true
  max_depth: 9

links_settings:
  title: 笔记总结

links:
  docker 相关: https://jueee.github.io/docker-doc/
  kubernetes 相关: https://jueee.github.io/kubernetes-doc/
  设计模式相关: https://jueee.github.io/design-patterns/
  Effective Java : https://jueee.github.io/effective-Java/
  Java 并发编程: https://jueee.github.io/ConcurrencyWithJava/
  Java 测试驱动开发: https://jueee.github.io/JavaTestDrivenDev/
  Java 8 函数式编程: https://jueee.github.io/Java8Lambdas/

# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

post_meta:
  updated_at:
    enable: false

symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: true

post_edit:
  enable: false
  url: https://github.com/Jueee/jueee-blog/edit/master/source/


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

mobile_layout_economy: true

codeblock:
  prism:
    light: prism-tomorrow
    dark: prism-tomorrow
  copy_button:
    enable: true
    style: flat

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

github_banner:
  enable: true
  permalink: https://github.com/Jueee/
  title: Fork me on GitHub


# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

index_with_subtitle: true

exturl: true

google_site_verification: EOcKnfaSWdV1p3pQylUZvIx2N977P3HKwO8tQCXWxUQ
bing_site_verification: 8093694B5A8E701B8D5816675F84CFFB
baidu_push: true

related_posts:
  enable: true
# ============================================================= #
# =============== Third Party Services Settings =============== #
# ============================================================= #

math:
  per_page: true
  mathjax:
    enable: true

pjax: true

mediumzoom: true


# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

comments:
  lazyload: true

disqus:
  enable: false
  shortname: theme-next
  count: true

valine:
  enable: true
  appId:  p5BeaWTTwjpAjNFu85LdGhaE-gzGzoHsz
  appKey:  UjjFeqPU2GMhIUJUYBh16SE0
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  meta: [nick, mail, link] # Custom comment header
  pageSize: 10 # pagination size
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html
  comment_count: true # If false, comment count will only be displayed in post page, not in home page
  recordIP: false # Whether to record the commenter IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)

# ============================================================= #
# ================= Statistics and Analytics （统计和分析）================== #
# ============================================================= #
# Google Analytics
google_analytics:
  tracking_id: UA-175024528-1
  only_pageview: false
# Baidu Analytics ID
baidu_analytics: d11c8b9bc802239c2cc46ff39d3faf79

# 不蒜子计数
busuanzi_count:
  enable: true
  total_visitors: true
  total_visitors_icon: fa fa-user
  total_views: true
  total_views_icon: fa fa-eye
  post_views: true
  post_views_icon: fa fa-eye
# ============================================================= #
# ====================== Search Services （搜索服务）====================== #
# ============================================================= #

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true

mermaid:
  enable: true

# ============================================================= #
# ==================== Chat Services （聊天服务）===================== #
# ============================================================= #
chatra:
  enable: false
  async: true
  id: 8nRWk5a2woHQ9j4g2
# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

motion:
  enable: true

vendors:
  anime: //cdn.jsdelivr.net/npm/animejs@3/lib/anime.min.js
  fontawesome: //cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css
